package com.clab.securecoding.type.etc;

public enum LogType {
    LOGIN,
    PARAMETER_ERROR,
    UN_AUTHORIZE_REQUEST_ERROR,
    LOGIN_FAILED_ERROR,
    SEARCH_RESULT_NOT_EXIST_ERROR,
    ASSOCIATED_ACCOUNT_EXISTS_EXCEPTION_ERROR,
    API_REQUEST_FAILED_EXCEPTION_ERROR,
    UN_EXCEPTED_ERROR,
    NOT_FOUND_EXCEPTION

}